repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/maltzj/ktlint-pre-commit
    rev: e5bee17
    hooks:
    -   id: ktlint
-   repo: https://github.com/maltzj/google-style-precommit-hook
    rev: b7e9e7fcba4a5aea463e72fe9964c14877bd8130
    hooks:
    -   id: google-style-java
-   repo: https://github.com/Cretezy/flutter-format-pre-commit
    rev: 4a1df675bb74dea371c17934933e257e46f8dd98
    hooks:
    -   id: flutter-format
